version: "3"

services:
    client:
      build: ./client
      container_name: react-ui
      ports:
        -  "3000:3000"
      stdin_open: true
      tty: true
      depends_on:
        - server
      networks:
        - mern-network

    server:
      build: ./server
      container_name: node-api
      restart: always
      ports:
        - "3001:3000"
      depends_on:
        - database
      networks:
        - mern-network

    database:
      image: mongo
      container_name: mongo-db
      ports:
        - "27017:27017"
      volumes:
        - /tdl_docker/mongo-backup:/data/db
      networks:
        - mern-network

networks:
  mern-network:
    driver: bridge